### ISSUE TITLE
effectiveValue always  auto strip whitespace for each item

### ISSUE THREAD

**Issue by mamh2021** [jenkinsci/extended-choice-parameter-plugin#81]
### Jenkins and plugins versions report
1.
for selectContent.jelly  `  <j:forEach var="value" items="${effectiveValue}"> `

ParameterDefinitionInfo.effectiveValue always auto strip  whitespace in forEach tag, so it will not match value  to description 

value is ` 111,22222            ,3333,444444`

description is `aaa,bbb,ccc,ddd`

2.
in computeDefaultValueMap method defaultValues  always trim

3.
in computeDescriptionPropertyValueMap method ,  the map keys not were trim

so I suggest make the three to same strategy

### What Operating System are you using (both controller, and any agents involved in the problem)?

extended-choice-parameter-plugin with the lastest source code at `df7ecf9 * Update pom.xml`

### Reproduction steps

select "Basic Parameter Types"
set value to   ` 111,22222            ,3333,444444`
set description to  `aaa,bbb,ccc,ddd`
![image](https://user-images.githubusercontent.com/16930340/224478607-6aea6795-efbd-4889-8aaa-a404469cbb4e.png)

### Expected Results

![image](https://user-images.githubusercontent.com/16930340/224478704-11464187-0461-471d-a666-0d15a5f54d02.png)

### Actual Results

![image](https://user-images.githubusercontent.com/16930340/224478663-f00ab688-9a7c-40b2-98d0-f8583e6c0668.png)

![image](https://user-images.githubusercontent.com/16930340/224478377-65881bdb-05ff-4b53-918b-49ecd89fb8c4.png)

**Comment by chonton** [comment]
Pull requests are welcome
